### ISSUE TITLE
Can't make a Texture from an Image for a Sprite2d

### ISSUE THREAD

**Issue by dsobiera** [godot-dlang/godot-dlang#152] opened 2023-11-07 17:29 UTC
OS: Ubuntu 22.04.3 LTS
Godot 4.1.2
dmd: v2.105.2

In GDScript, this makes a red image:

	var myPackedByteArray : PackedByteArray
	
	const WIDTH : int = 1280
	const HEIGHT: int = 720
	
	for i in HEIGHT:
		for j in WIDTH:
			myPackedByteArray.append(255)
			myPackedByteArray.append(0)
			myPackedByteArray.append(0)
	
	var mySprite : Sprite2D = get_node("mySprite")	
	var myImage : Image = Image.create_from_data(WIDTH, HEIGHT, false, Image.FORMAT_RGB8, myPackedByteArray)	
	var myTexture2d : Texture2D = ImageTexture.create_from_image(myImage)	
	mySprite.texture = myTexture2d

I try this in D:
            PackedByteArray myPackedByteArray;

            const uint WIDTH  = 1280;
            const uint HEIGHT = 720;

           for (uint i = 0; i < HEIGHT; i++) {
               for (uint j = 0; j < WIDTH; j++) {
                   myPackedByteArray.append(255);
                   myPackedByteArray.append(0);
                   myPackedByteArray.append(0);
               }
           }

           Sprite2D mySprite = getNodeOrNull("mySprite").as!Sprite2D;
           if (mySprite != null) {
               print("FOUND!");
           } else {
               print("Sprite not found");
               return;
           }
           Image myImage = Image.createFromData(WIDTH, HEIGHT, false, Image.Format.formatRgb8, myPackedByteArray);
           Texture2D myTexture2d = ImageTexture.createFromImage(myImage);

           // I also tried mySprite.setTexture(myTexture2d) and got the same ERROR
           mySprite.texture = myTexture2d;

and I get:

WARNING: FOUND!
     at: godottest.GodotTest._ready (source/godottest.d:76)
ERROR: Invalid image: null
   at: create_from_image (scene/resources/texture.cpp:171)
   
Any idea what I am doing wrong?

**Comment by Superbelko** [comment] 2023-11-08 08:30
The problem is implicit cast from `Ref!` container to a plain resource type, what is happening is that calls such as `Image.createFromData` and `ImageTexture.createFromImage` returns refcounted resource which immediately released and effectively this variable contains null.

I should probably tinker with it a bit to prohibit such casts in the future.

Anyway here is a corrected example, notice the `Ref!` variables, of course you can use auto as well.
```d
Sprite2D mySprite = getNodeOrNull("mySprite").as!Sprite2D;
Ref!Image myImage = Image.createFromData(WIDTH, HEIGHT, false, Image.Format.formatRgb8, myPackedByteArray);
Ref!Texture2D myTexture2d = ImageTexture.createFromImage(myImage);
mySprite.texture = myTexture2d;
```

**Comment by Superbelko** [comment] 2023-11-08 09:04
To other contributors:
It leaks through alias this in Ref.refPayload, it also hides potential problems with various getters properties such as this one

```d
class AnimatedSprite2D {
    // ...
    @property SpriteFrames spriteFrames() {
        return getSpriteFrames(); // <- returns Ref!SpriteFrames, immediately released and is effectively null
    }
}
```

**Comment by Superbelko** [comment] 2023-11-08 10:29
At this moment it seems not possible to enforce it to work without escaping scope, marking this issue as won't fix for now.

**Comment by dsobiera** [comment] 2023-11-08 16:01
Changing to Ref! did fix the issue for me.  I'm normally not one that likes to use auto (I like knowing my data types pre build :)  ) but I'll keep that in mind if this becomes an on-going problem for me. 

Thanks again for looking into this.

**Closed** 2023-11-08 16:02 UTC
Labels: wontfix
